name: Diplomacy
main: me.tedwoodworth.diplomacy.Diplomacy
version: 0.1.0

api-version: 1.16
depend: [ Vault, dynmap ]

commands:
  plot:
    description: Manage a plot.
    aliases: [p]
    usage: "Usage: /<command> ..."

  nation:
    description: Manage a nation.
    aliases: [n]
    usage: "Usage: /<command> ..."

  group:
    description: Manage a group.
    aliases: [g]
    usage: "Usage: /<command> ..."

  wallet:
    description: Check your wallet.
    aliases: []
    usage: "Usage: /<command>"

  pay:
    description: Pay another player.
    aliases: []
    usage: "Usage: /<command> ..."

  deposit:
    description: Deposit money into the bank.
    aliases: []
    usage: "Usage: /<command> ..."

  withdraw:
    description: Withdraw money from the bank.
    aliases: []
    usage: "Usage: /<command> ..."

  menu:
    description: Open the diplomacy menu.
    aliases: []
    usage: "Usage: /<command>"

  class:
    description: Manage classes.
    aliases: []
    usage: "Usage: /<command> ..."

  gc:
    description: Enter global Chat.
    aliases: []
    usage: "Usage: /<command>"

  ac:
    description: Enter ally Chat.
    aliases: []
    usage: "Usage: /<command>"

  nc:
    description: Enter nation Chat.
    aliases: []
    usage: "Usage: /<command>"

  lc:
    description: Enter local Chat.
    aliases: []
    usage: "Usage: /<command>"

  lives:
    description: Get your lives.
    aliases: []
    usage: "Usage: /<command>"

  giveLives:
    description: Give another player lives.
    aliases: []
    usage: "Usage: /<command>"

  ott:
    description: Teleport to another player.
    aliases: []
    usage: "Usage: /<command>"

  ottConfirm:
    description: Confirm using ott.
    aliases: []
    usage: "Usage: /<command>"

  ottCancel:
    description: Cancel using ott.
    aliases: []
    usage: "Usage: /<command>"

  ottAccept:
    description: Accept an ott request.
    aliases: []
    usage: "Usage: /<command>"

  ottDecline:
    description: Decline an ott request.
    aliases: []
    usage: "Usage: /<command>"

  tag:
    description: Send combat log tag message.
    aliases: []
    usage: "Usage: /<command>"

  untag:
    description: Send combat log untag message.
    aliases: []
    usage: "Usage: /<command>"


